server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7001.com:7001/eureka,http://eureka7001.com:7001/eureka
spring:
  http:
    encoding:
      force: true
      charset: utf-8
