server:
  port: 8082
mybatis:
  type-aliases-package: com.com.lzh.springcloud.pojo
  config-location: classpath:mybatis/mybaits.config-xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    username: root
    password: 7777777..
    url: jdbc:mysql://localhost:3306/db02?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7001.com:7001/eureka,http://eureka7001.com:7001/eureka
  instance:
    instance-id: springboot-provider-dept-8002
info:
  app.name: liuyi-springCloud
  company.name: www.bestliu.cn