server:
  port: 9527
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7001.com:7001/eureka,http://eureka7001.com:7001/eureka
  instance:
    instance-id: zuul9527.com
info:
  app.name: liuyi-springCloud
  company.name: www.bestliu.cn
spring:
  application:
    name: springcloud-zuul
zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: "*"   # 如果设置了 *，所有的请求都必须经由网关进行访问，不可以再访问原来的地址
  prefix: /liuyi          # 为所有路径设置前缀
  # 原路径：http://www.bsetliu.com:9527/mydept/dept/queryAll
  # 加上前缀后：http://www.bsetliu.com:9527/liuyi/mydept/dept/queryAll